[SystemSettings]
; --- LUMA - DLSS/FSR upscaling ---
r.DynamicRes.OperationMode=0
r.DynamicRes.MinScreenPercentage=100
r.TemporalAASamples=8

[/Script/Engine.RendererSettings]
; --- Otimizações de Streaming e VRAM para evitar Stuttering de Travessia ---
r.Streaming.PoolSize=0
r.Streaming.LimitPoolSizeToVRAM=1
r.Streaming.UseAsyncRequestsForDDC=1
r.Streaming.AmortizeCPUToGPUCopy=1
r.Streaming.DefragDynamicBounds=1
r.UseShaderCaching=1
r.CreateShadersOnLoad=1
r.ShaderComplexity.CacheShaders=1

; --- Threading e Shaders (Otimizado para Proton/Linux) ---
r.AsyncCompute=1
r.UseAsyncShaderPrecompilation=1
r.ShaderPipelineCache.Enabled=1
r.ShaderPipelineCache.PreOptimizeEnabled=1
r.RDG.AsyncCompute=1
r.VolumetricRenderTarget.PreferAsyncCompute=1

[Core.System]
+Suppress=ScriptWarning
+Suppress=Error
+Suppress=ScriptLog
+Suppress=Warning

[ConsoleVariables]
; --- 1. DLSS / FSR ---
r.DynamicRes.OperationMode=0
r.DynamicRes.MinScreenPercentage=100

; --- 2. FPS / VSYNC (Deixando o MangoHud/DXVK controlar) ---
t.MaxFPS=0
r.VSync=0
rhi.SyncInterval=0

; --- 3. SOMBRAS (Equilíbrio entre Alta Qualidade e Performance de CPU) ---
r.Shadow.MaxResolution=2048
r.Shadow.MaxCSMResolution=2048
r.Shadow.DistanceScale=1.0
r.Shadow.CSM.MaxCascades=2

; --- 4. TEXTURAS E REFLEXOS ---
r.MaxAnisotropy=16
r.SSR.Quality=3

; --- 5. IMAGEM LIMPA (Desativando efeitos borrados) ---
r.MotionBlurQuality=0
r.Tonemapper.GrainQuantization=0
r.DepthOfFieldQuality=0
r.DepthOfField.FarBlur=0